### ISSUE TITLE
About image not drawing

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#57]
On OSX, even though it recognizes the click in the about button and loads the image, it's not drawing.

**Comment by Oscar-Rodrigues** [comment]
This happens because ofApp::touchDown() is being called twice in a row, so it changes the inAbout bool to true and then, right after that,back to false.

**Comment by Oscar-Rodrigues** [comment]
@nunoh could you please check this? In my computer, all of the methods that get ofTouchEventArgs as an argument are being double called - ofApp::touchDown, ofApp::touchMoved and ofApp::touchUp

**Comment by nunoh** [comment]
With the lastest `master` version this is not happening for me. I can see the about message no problem.

@Oscar-Rodrigues please double check if you do have in fact the latest version. Not sure if you are aware of the "trick" we are employing so that the app works ok with mouse and multitouch (both in acer screen and for future mobile versions). Basically, what happens when running the app in a computer, the mouse callbacks triggered are the `mousePressed`, `mouseDragged` and `mouseReleased`, which function basically as a wrapper to the equivalent `touchDown`, `touchMoved` and `touchUp`, so that we have the code all in one place.

**Comment by nunoh** [comment]
@Oscar-Rodrigues try with `stable` branch of OF (version 0.8.4) and report if ok or not

**Comment by Oscar-Rodrigues** [comment]
@nunoh just tested it and it's running ok with 0.8.4

**Comment by nunoh** [comment]
Nice :+1: Closing this issue then.
