### ISSUE TITLE
Match the size of the touch and the particle when it's released

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#67]
This has never been correctly working, as far as I can remember. It just looks odd when releasing a touch and the particle that is created is of a slightly different size than of the touch (before it being released).

**Comment by Oscar-Rodrigues** [comment]
This was because we were using different functions to create the circles. Touch.cpp used the ofEllipse(x, y, width, height), which, in practice, deals with the diameter, whereas Particle.cpp uses ofCircle(x, y, radius), which deals with radius. I also created a new constant, PARTICLE_OFFSET (set to the 1.05 @nunoh entered) so that they both report to the same value.
