### ISSUE TITLE
Change App icon

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#75]
IMO we should go with the particle icon suggestion Nuno. Take a screenshot of one or two or three Particles, create a png with transparency and use it as an icon.

**Comment by nunoh** [comment]
I had done exactly what you say some time ago and send it by mail (see below). But since there was someone working on a more official icon (I assume designer), we never though about it again.

But why Semibreve @Oscar-Rodrigues? The app is going to be on all the time so no one is triggering the application from an icon. Or you mean to use it to replace to what is beneath the "Gamult" text in the about screen?

icon-suggestion-1
![icon-suggestion-1](https://cloud.githubusercontent.com/assets/1161423/10775106/d8122232-7cfd-11e5-8d7a-865d4145367b.png)

icon-suggestion-2
![icon-suggestion-2](https://cloud.githubusercontent.com/assets/1161423/10775107/d814145c-7cfd-11e5-98e2-032206ba5403.png)

**Comment by Oscar-Rodrigues** [comment]
I know you did, that's why I meant "we should go with Nuno's suggestion". Bad phrasing :) I think we should have it done ASAP just so that if we need to present it it's ready.

**Comment by nunoh** [comment]
But once again @Oscar-Rodrigues, unless I am missing something, this is for Mobile release and not for Semibreve, since in Semibreve the icon for launching the app doesn't apply.

**Comment by nunoh** [comment]
@jasgomes Any news on this?

**Comment by jasgomes** [comment]
Tiago already made the icon.
What is missing?

---

www.jasg.net

No dia 08/01/2016, às 17:11, Nuno Hespanhol notifications@github.com escreveu:

**Comment by nunoh** [comment]
Really? Nice! But where is it then? So that we can add it to the repo and app. Can't seem to find it neither in GH or in any email thread.

**Comment by jasgomes** [comment]
It's the icon that is already in the software. In the information page probably or at the beginning

---

www.jasg.net

No dia 10/01/2016, às 11:01, Nuno Hespanhol notifications@github.com escreveu:

**Comment by nunoh** [comment]
Oh ok! We'll take a look at it and close this next Digi I guess. Cheers

**Comment by nunoh** [comment]
I'll ask Tiago (the designer) to do this since I don't really know how to perfectly center the icon in Photoshop. :joy: 

Guess it should take him like 2 seconds to do it.

**Comment by nunoh** [comment]
(in progress as need to change background of icon from transparent to the one in the background image, since in iOS transparent it's not really a good option.)

**Comment by nunoh** [comment]
Reopening as simply setting the background to white, doesn't really look nice at all. Therefore, forwarding this to Tiago Carneiro again.

![img_0209](https://cloud.githubusercontent.com/assets/1161423/13458843/bf4015c0-e067-11e5-90ed-1c416197c263.PNG)

**Comment by nunoh** [comment]
Ended up not sending to Tiago Carneiro after all. As putting a border around the image make it good enough, for me at least.

![img_0210](https://cloud.githubusercontent.com/assets/1161423/13459118/5a8cd102-e069-11e5-8993-c5313be9b5b3.PNG)
