### ISSUE TITLE
Make images show up in iOS

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#84]

**Comment by Oscar-Rodrigues** [comment]
This is due to the size of the images. 

FYI, I'm copying the explanation in portuguese

O seguinte código devolvia-me true, pelo que deduzi que ele estava a carregar as imagens.

```
bool checkLoadAbout = imgAbout.load("images/about7.png");
cout << checkLoadAbout << endl;
```

Então o problema era a desenhar ou a aceder aos recursos.

Isto parecia-me óbvio por três razões:

I) porque as setas estavam a ser desenhadas, pelo que ele estava, de certeza a encontrar as imagens;
II) não me dava o erro de drawing an unallocated texture;
III) a imagem desenhada era branca e não aquele cinzento marado do costume.

Assumindo isto como óbvio, verifiquei se o código responsável pelo desenho estava a correr, e estava. 

Então, porque é que ele desenhava as setas e não as imagens “grandes”? Verifiquei que as imagens grandes têm uma resolução de 5333x3000 (!!!!!!). Inclui este código:

```
imgAbout.load("images/about7.png");
imgAbout.resize(ofGetWidth(), ofGetHeight());
```

E passou tudo a funcionar sem problema!

**Comment by nunoh** [comment]
Impecável Óscar! Segui exatamente o mesmo raciocínio que tu ontem, só com a excepção do último passo. A tua solução basicamente implica que ao contrário do que acontece na versão of 0.8 em que `imgAbout.draw(0, 0, ofGetWidth(), ofGetHeight)` faz o resize under the hood, o mesmo não acontece para a versão 0.9, sendo necessário fazer esse resize em separado. E isso eu nunca pus em causa, porque para além de me parecer estúpido da parte do OF, simplesmente não me ocorreu. Vou fazer um MWE (minimal working example) com isso e criar um issue no repo deles, para fazerem fix, que isto não tem jeito nenhum! :smile:
